const STORAGE_KEY = 'folio-mvp-v1';
const seed = {
  profile:{name:'김취준',role:'프론트엔드 개발자',target:'사용자 경험을 기술로 개선하는 프론트엔드 개발자',email:'career@example.com',phone:'010-1234-5678',location:'서울',education:'한국대학교 컴퓨터공학과',period:'2020.03 — 2026.02',links:['github.com/career','portfolio.example.com'],skills:['React','TypeScript','Next.js','JavaScript','Git']},
  stories:[
    {id:'s1',title:'검색 전환율 개선',role:'프론트엔드 개발 · 커머스 프로젝트',skills:['React','TypeScript','A/B 테스트'],summary:'검색 결과의 렌더링 병목을 개선하고 필터 UX를 재설계해 상품 탐색 시간을 32% 단축했습니다.'},
    {id:'s2',title:'디자인 시스템 구축',role:'UI 플랫폼 · 사이드 프로젝트',skills:['React','Storybook','접근성'],summary:'24개 공통 컴포넌트를 문서화하고 재사용해 신규 화면 제작 시간을 약 40% 줄였습니다.'},
    {id:'s3',title:'실시간 협업 보드',role:'팀 프로젝트 · 프론트엔드 리드',skills:['Next.js','WebSocket','상태관리'],summary:'5인 팀의 프론트엔드 구조를 설계하고 실시간 동기화 충돌을 해결해 안정적인 협업 기능을 구현했습니다.'}
  ],
  jobs:[
    {id:'j1',company:'토스',role:'Frontend Developer',deadline:'2026-08-09',url:'',description:'React와 TypeScript 기반 제품 개발, 사용자 경험 개선, 성능 최적화 경험. 디자인 시스템 및 협업 경험 우대.',skills:['React','TypeScript','사용자 경험','성능 최적화','디자인 시스템'],match:92,status:'관심'},
    {id:'j2',company:'당근',role:'Software Engineer, Web',deadline:'2026-08-14',url:'',description:'Next.js 기반 웹 서비스 개발, 실시간 인터랙션 구현, 제품 지표 개선 경험.',skills:['Next.js','WebSocket','제품 지표','React'],match:84,status:'작성 중'},
    {id:'j3',company:'무신사',role:'Frontend Engineer',deadline:'2026-08-21',url:'',description:'TypeScript, React를 활용한 커머스 플랫폼 개발. A/B 테스트 및 성능 개선 경험 우대.',skills:['TypeScript','React','A/B 테스트','커머스'],match:78,status:'지원 완료'}
  ],
  applications:[
    {id:'a1',jobId:'j1',status:'관심',next:'지원 여부 결정'},
    {id:'a2',jobId:'j2',status:'작성 중',next:'자소서 검토'},
    {id:'a3',jobId:'j3',status:'지원 완료',next:'결과 대기'},
    {id:'a4',jobId:'j4',status:'면접',next:'기술 면접 준비',custom:{company:'카카오페이',role:'Frontend Developer',deadline:'2026-08-07',match:88}},
    {id:'a5',jobId:'j5',status:'탈락',next:'회고 작성',custom:{company:'네이버',role:'Frontend Engineer',deadline:'2026-07-20',match:76}}
  ],
  tasks:[
    {id:'t1',text:'당근 자기소개서 최종 검토',date:'오늘',done:false},
    {id:'t2',text:'카카오페이 기술 면접 준비',date:'D-3',done:false},
    {id:'t3',text:'무신사 지원서 제출',date:'완료',done:true}
  ],
  docs:[
    {id:'d1',title:'당근 · 지원 동기',jobId:'j2',content:'저는 사용자의 일상에 가까운 문제를 기술로 해결하는 과정에 큰 동기를 느낍니다. 실시간 협업 보드를 개발하며 WebSocket 동기화 충돌을 해결했고, 5인 팀의 프론트엔드 구조를 설계했습니다. 이 경험을 바탕으로 지역 커뮤니티의 복잡한 상호작용을 빠르고 안정적인 웹 경험으로 구현하고 싶습니다.'},
    {id:'d2',title:'토스 · 직무 역량',jobId:'j1',content:'검색 결과 렌더링 병목을 개선하고 필터 UX를 재설계해 상품 탐색 시간을 32% 단축했습니다. 성능 지표와 사용자 행동을 함께 관찰해 가설을 세우고 검증한 경험은, 사용자 중심으로 빠르게 실험하는 제품 개발에 기여할 수 있는 저의 강점입니다.'}
  ],
  interviews:[
    {id:'i1',company:'카카오페이',role:'Frontend Developer',date:'2026-08-07',type:'기술 면접',prepared:6},
    {id:'i2',company:'무신사',role:'Frontend Engineer',date:'2026-08-18',type:'직무 인터뷰',prepared:2}
  ]
};
let state = load(); let currentView='home'; let selectedJob=null; let selectedDoc=state.docs[0]?.id;
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved)return structuredClone(seed);saved.profile={...seed.profile,...saved.profile};if(!saved.applications.some(a=>a.status==='탈락'))saved.applications.push(structuredClone(seed.applications.find(a=>a.status==='탈락')));return saved}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function fmtDate(v){if(!v)return '-';return new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric'}).format(new Date(v+'T00:00:00'))}
function days(v){return Math.ceil((new Date(v+'T23:59:59')-new Date())/86400000)}
function getJob(app){return state.jobs.find(j=>j.id===app.jobId)||app.custom}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function setView(view){currentView=view;selectedJob=null;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));render()}
function render(){const views={home:renderHome,career:renderCareer,jobs:renderJobs,applications:renderApplications,documents:renderDocuments,interviews:renderInterviews,calendar:renderCalendar};const content=$('#appContent');content.classList.toggle('home-view',currentView==='home'&&!selectedJob);content.innerHTML=selectedJob?renderJobDetail(selectedJob):(views[currentView]||renderHome)();bindDynamic()}
function head(kicker,title,sub){return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${sub}</p></div><span class="date-chip">${new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date())}</span></div>`}
function renderHome(){const writing=state.applications.filter(a=>['관심','작성 중'].includes(a.status)).length;const interviews=state.applications.filter(a=>a.status==='면접').length;const results=state.applications.filter(a=>['탈락','합격'].includes(a.status)).length;return `<div class="page-head compact-head"><div><h1>홈</h1></div><span class="date-chip">${new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date())}</span></div>
  <div class="grid stats-grid home-stats"><button class="card stat stat-link highlight" data-go="applications"><div class="label">서류 작성 중</div><div class="value">${writing}<span class="unit">건</span></div><span class="stat-arrow">→</span></button><button class="card stat stat-link" data-go="applications"><div class="label">전체 지원</div><div class="value">${state.applications.length}<span class="unit">건</span></div><span class="stat-arrow">→</span></button><button class="card stat stat-link" data-go="interviews"><div class="label">면접 진행</div><div class="value">${interviews}<span class="unit">건</span></div><span class="stat-arrow">→</span></button><button class="card stat stat-link" data-go="applications"><div class="label">결과 확인</div><div class="value">${results}<span class="unit">건</span></div><span class="stat-arrow">→</span></button></div>
  <div class="grid dashboard-grid home-panels"><article class="card"><div class="section-head"><h2>다가오는 일정</h2><button class="text-button" data-go="calendar">달력 보기 →</button></div>${calendarEvents().slice(0,4).map(e=>`<button class="schedule-row" data-go="calendar"><time><b>${new Date(e.date+'T00:00:00').getDate()}</b>${new Intl.DateTimeFormat('ko-KR',{month:'short'}).format(new Date(e.date+'T00:00:00'))}</time><span><strong>${esc(e.title)}</strong><small>${esc(e.detail)}</small></span><i>${days(e.date)>=0?`D-${days(e.date)}`:'완료'}</i></button>`).join('')}</article>
  <article class="card"><div class="section-head"><h2>할 일</h2><button class="text-button" data-action="add-task">+ 추가</button></div><div class="task-list">${state.tasks.map(t=>`<label class="task ${t.done?'done':''}"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span>${esc(t.text)}</span><time>${esc(t.date)}</time></label>`).join('')}</div><div class="progress-wrap"><div class="progress-label"><span>완료</span><b>${taskProgress()}%</b></div><div class="progress"><i style="width:${taskProgress()}%"></i></div></div></article></div>`}
function taskProgress(){return Math.round(state.tasks.filter(t=>t.done).length/(state.tasks.length||1)*100)}
function jobRow(j){return `<div class="job-row" data-job="${j.id}"><div class="company-logo">${esc(j.company.slice(0,1))}</div><div><strong>${esc(j.company)} · ${esc(j.role)}</strong><small>${fmtDate(j.deadline)} 마감 · ${j.skills.slice(0,2).join(', ')}</small></div><span>→</span></div>`}
function renderCareer(){const p=state.profile;return `${head('MY INFORMATION','내 정보','지원할 때 반복해서 입력하는 정보를 한곳에서 관리합니다.')}<form id="profileForm" class="resume-sheet"><section class="resume-header"><div class="resume-avatar">${esc(p.name?.[0]||'나')}</div><div><input name="name" value="${esc(p.name)}" aria-label="이름"><input class="role-input" name="role" value="${esc(p.role)}" aria-label="희망 직무"></div><button class="button primary" type="submit">저장</button></section><section class="resume-section"><h2>기본 정보</h2><div class="resume-fields"><label>이메일<input name="email" value="${esc(p.email||'')}"></label><label>연락처<input name="phone" value="${esc(p.phone||'')}"></label><label>거주 지역<input name="location" value="${esc(p.location||'')}"></label><label>한 줄 소개<input name="target" value="${esc(p.target||'')}"></label></div></section><section class="resume-section"><h2>학력</h2><div class="resume-fields"><label>학교 및 전공<input name="education" value="${esc(p.education||'')}"></label><label>재학 기간<input name="period" value="${esc(p.period||'')}"></label></div></section><section class="resume-section"><div class="section-head"><h2>기술</h2></div><input name="skills" value="${esc((p.skills||[]).join(', '))}" placeholder="쉼표로 구분해 입력하세요"><div class="tag-row profile-tags">${(p.skills||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></section><section class="resume-section"><div class="section-head"><h2>경력 및 프로젝트</h2><button class="text-button" type="button" data-action="open-career-modal">+ 추가</button></div>${state.stories.map(s=>`<article class="resume-experience"><div><strong>${esc(s.title)}</strong><small>${esc(s.role)}</small></div><p>${esc(s.summary)}</p><div class="tag-row">${s.skills.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></article>`).join('')}</section><section class="resume-section"><h2>이력서 · 포트폴리오</h2><div class="asset-list"><button type="button"><span>PDF</span><div><strong>기본 이력서.pdf</strong><small>최근 수정 · 오늘</small></div><i>열기</i></button>${(p.links||[]).map((x,i)=>`<button type="button"><span>URL</span><div><strong>${i===0?'GitHub':'포트폴리오'}</strong><small>${esc(x)}</small></div><i>열기</i></button>`).join('')}</div></section></form>`}
function renderJobs(){return `${head('JOB ARCHIVE','공고 보관함','나중에 확인할 채용 공고를 저장합니다.')}<div class="filters"><button class="filter active">전체 ${state.jobs.length}</button><button class="filter">마감 임박</button></div><div class="grid list-grid">${state.jobs.map(j=>`<article class="card posting-card" data-job="${j.id}" style="cursor:pointer"><div class="section-head"><div class="company-logo">${esc(j.company[0])}</div><span class="deadline">${days(j.deadline)>=0?`D-${days(j.deadline)}`:'마감'}</span></div><h3>${esc(j.company)}</h3><strong>${esc(j.role)}</strong><p>${esc(j.description.slice(0,95))}${j.description.length>95?'…':''}</p><div class="tag-row">${j.skills.slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></article>`).join('')}<button class="card empty-add" data-action="open-job-modal"><span><b>＋</b>공고 가져오기</span></button></div>`}
function renderJobDetail(id){const j=state.jobs.find(x=>x.id===id);if(!j)return renderJobs();const matches=matchRequirements(j);return `<button class="text-button" data-action="back">← 공고 목록</button><div class="detail-hero" style="margin-top:18px"><p class="eyebrow">JOB POSTING</p><h2>${esc(j.company)} · ${esc(j.role)}</h2><p>${fmtDate(j.deadline)} 마감 · 저장된 공고 원문</p><div class="detail-meta">${j.skills.map(s=>`<span>${esc(s)}</span>`).join('')}</div></div><div class="grid dashboard-grid"><article class="card"><div class="section-head"><h2>주요 요구사항</h2></div><div class="requirements">${matches.map(x=>`<div class="requirement"><span>•</span><div><b>${esc(x.skill)}</b><small style="display:block;margin-top:4px">${x.story?esc('관련 경험: '+x.story.title):'관련 경험을 내 정보에 추가할 수 있습니다.'}</small></div></div>`).join('')}</div></article><article class="card"><div class="section-head"><h2>공고 원문</h2></div><p class="muted" style="font-size:13px">${esc(j.description)}</p><div style="display:grid;gap:8px;margin-top:20px"><button class="button primary" data-action="apply" data-id="${j.id}">지원 건 만들기</button><button class="button" data-action="draft" data-id="${j.id}">맞춤 초안 만들기</button></div></article></div>`}
function matchRequirements(job){return job.skills.map(skill=>({skill,story:state.stories.find(s=>s.skills.some(x=>x.toLowerCase().includes(skill.toLowerCase())||skill.toLowerCase().includes(x.toLowerCase())))}))}
function supportTabs(active){return `<div class="section-tabs"><button class="${active==='applications'?'active':''}" data-go="applications">지원 현황</button><button class="${active==='documents'?'active':''}" data-go="documents">지원 문서</button></div>`}
function renderApplications(){const statuses=['관심','작성 중','지원 완료','서류 통과','면접','합격','탈락'];return `${head('APPLICATIONS','지원 관리','작성 중인 서류부터 종료된 지원까지 모두 기록합니다.')}${supportTabs('applications')}<div class="application-summary">${statuses.map(st=>`<span><b>${state.applications.filter(a=>a.status===st).length}</b>${st}</span>`).join('')}</div><div class="application-list">${state.applications.map(a=>{const j=getJob(a);return `<article class="application-row"><div class="app-company"><div class="company-logo">${esc(j.company[0])}</div><div><strong>${esc(j.company)}</strong><small>${esc(j.role)}</small></div></div><span class="status status-${statusClass(a.status)}">${a.status}</span><span class="app-next"><small>다음 할 일</small>${esc(a.next)}</span><span class="app-date"><small>마감일</small>${fmtDate(j.deadline)}</span><select data-app-status="${a.id}" aria-label="상태 변경">${statuses.map(x=>`<option ${x===a.status?'selected':''}>${x}</option>`).join('')}</select></article>`}).join('')}</div>`}
function statusClass(s){return s==='탈락'?'closed':s==='합격'?'success':s==='면접'?'interview':s.includes('작성')?'writing':'default'}
function renderDocuments(){const doc=state.docs.find(d=>d.id===selectedDoc)||state.docs[0];return `${head('APPLICATIONS','지원 관리','회사별 지원 문서를 확인하고 편집합니다.')}${supportTabs('documents')}<div class="doc-layout"><aside class="card doc-list company-doc-list"><div class="section-head"><h2>회사별 문서</h2><button class="text-button" data-action="new-doc">＋</button></div>${state.docs.map(d=>{const j=state.jobs.find(j=>j.id===d.jobId);return `<button class="${d.id===doc?.id?'active':''}" data-doc="${d.id}"><span class="company-logo">${esc((j?.company||d.title)[0])}</span><span><strong>${esc(j?.company||d.title.split(' · ')[0])}</strong><small>${esc(d.title.split(' · ')[1]||'지원 문서')}</small></span></button>`}).join('')}</aside><article class="card editor">${doc?`<div class="editor-toolbar"><div><p class="eyebrow">APPLICATION DOCUMENT</p><strong>${esc(doc.title)}</strong></div><button class="button small" data-action="save-doc">버전 저장</button></div><textarea id="docEditor" data-id="${doc.id}">${esc(doc.content)}</textarea><div class="word-count"><span id="charCount">${doc.content.length}</span>자 · 자동 저장됨</div>`:'<p class="muted">문서를 새로 만들어 시작하세요.</p>'}</article></div>`}
function renderInterviews(){return `${head('INTERVIEWS','면접','면접 일정과 실제 질문 및 회고를 관리합니다.')}<article class="card"><div class="section-head"><h2>면접 일정</h2><button class="text-button" data-go="calendar">달력 보기 →</button></div>${state.interviews.map(i=>`<div class="interview-row"><div class="interview-date"><b>${fmtDate(i.date)}</b><br>${days(i.date)>=0?`D-${days(i.date)}`:'완료'}</div><div><h3>${esc(i.company)} · ${esc(i.type)}</h3><p>${esc(i.role)} · 질문 및 답변 ${i.prepared}개 기록</p></div><button class="button small" data-action="prepare" data-id="${i.id}">기록 보기</button></div>`).join('')}</article>`}
function calendarEvents(){return [...state.jobs.map(j=>({date:j.deadline,title:`${j.company} 지원 마감`,detail:j.role,type:'deadline'})),...state.interviews.map(i=>({date:i.date,title:`${i.company} ${i.type}`,detail:i.role,type:'interview'}))].sort((a,b)=>a.date.localeCompare(b.date))}
function renderCalendar(){const events=calendarEvents();const base=new Date();const y=base.getFullYear(),m=base.getMonth();const first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();const cells=Array.from({length:first},()=>null).concat(Array.from({length:last},(_,i)=>i+1));return `${head('SCHEDULE','일정','지원 마감과 면접 일정을 달력으로 확인합니다.')}<div class="calendar-layout"><section class="card calendar"><div class="calendar-head"><button>‹</button><h2>${y}년 ${m+1}월</h2><button>›</button></div><div class="weekdays">${['일','월','화','수','목','금','토'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells.map(d=>d?`<div class="calendar-day ${d===base.getDate()?'today':''}"><b>${d}</b>${events.filter(e=>new Date(e.date+'T00:00:00').getFullYear()===y&&new Date(e.date+'T00:00:00').getMonth()===m&&new Date(e.date+'T00:00:00').getDate()===d).map(e=>`<span class="event ${e.type}">${esc(e.title)}</span>`).join('')}</div>`:'<div class="calendar-day empty"></div>').join('')}</div></section><aside class="card agenda"><div class="section-head"><h2>예정된 일정</h2></div>${events.slice(0,6).map(e=>`<div class="agenda-row"><time>${fmtDate(e.date)}</time><span><strong>${esc(e.title)}</strong><small>${esc(e.detail)}</small></span></div>`).join('')}</aside></div>`}
function bindDynamic(){document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>setView(x.dataset.go));document.querySelectorAll('[data-job]').forEach(x=>x.onclick=()=>{selectedJob=x.dataset.job;render()});document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>{const t=state.tasks.find(t=>t.id===x.dataset.task);t.done=x.checked;save();render()});document.querySelectorAll('[data-app-status]').forEach(x=>x.onchange=()=>{state.applications.find(a=>a.id===x.dataset.appStatus).status=x.value;save();render();toast('지원 상태를 변경했습니다.')});document.querySelectorAll('[data-doc]').forEach(x=>x.onclick=()=>{selectedDoc=x.dataset.doc;render()});const ed=$('#docEditor');if(ed)ed.oninput=()=>{$('#charCount').textContent=ed.value.length;const d=state.docs.find(x=>x.id===ed.dataset.id);d.content=ed.value;save()};const pf=$('#profileForm');if(pf)pf.onsubmit=e=>{e.preventDefault();const f=new FormData(pf);['name','role','email','phone','location','target','education','period'].forEach(k=>state.profile[k]=f.get(k));state.profile.skills=f.get('skills').split(',').map(x=>x.trim()).filter(Boolean);save();$('#sidebarName').textContent=state.profile.name;$('#sidebarRole').textContent=state.profile.role;toast('내 정보를 저장했습니다.')};document.querySelectorAll('[data-action]').forEach(x=>x.onclick=e=>handleAction(e,x))}
function handleAction(e,el){const a=el.dataset.action;if(['open-job-modal','open-career-modal','open-mobile-menu','close-mobile-menu','add-task','reset','back','apply','draft','new-doc','save-doc','mock','prepare'].includes(a))e.preventDefault();if(a==='open-job-modal'){$('#jobModal').showModal()}if(a==='open-career-modal'){$('#careerModal').showModal()}if(a==='open-mobile-menu'){$('#mobileMenu').showModal()}if(a==='close-mobile-menu'){$('#mobileMenu').close()}if(a==='back'){selectedJob=null;render()}if(a==='apply'){createApplication(el.dataset.id)}if(a==='draft'){createDraft(el.dataset.id)}if(a==='add-task'){const text=prompt('추가할 일을 입력하세요.');if(text){state.tasks.unshift({id:'t'+Date.now(),text,date:'오늘',done:false});save();render()}}if(a==='new-doc'){state.docs.unshift({id:'d'+Date.now(),title:'새 자기소개서',content:'문항의 핵심 메시지를 적어보세요.'});selectedDoc=state.docs[0].id;save();render()}if(a==='save-doc')toast('현재 내용을 새 버전으로 저장했습니다.');if(a==='mock')toast('MVP에서는 질문 준비 기능을 먼저 제공합니다.');if(a==='prepare')toast('공고와 제출 문서를 바탕으로 예상 질문을 준비했습니다.');if(a==='reset'&&confirm('저장한 내용을 데모 데이터로 초기화할까요?')){state=structuredClone(seed);save();setView('home')}}
function createApplication(jobId){if(state.applications.some(a=>a.jobId===jobId)){toast('이미 지원 관리에 등록된 공고입니다.');return}state.applications.unshift({id:'a'+Date.now(),jobId,status:'관심',next:'지원 여부 결정'});save();toast('지원 관리에 추가했습니다.');setTimeout(()=>setView('applications'),500)}
function createDraft(jobId){const job=state.jobs.find(j=>j.id===jobId);const matched=matchRequirements(job).filter(x=>x.story).map(x=>x.story);const unique=[...new Map(matched.map(x=>[x.id,x])).values()];const body=unique.length?`${job.company}의 ${job.role} 직무에서 요구하는 ${job.skills.slice(0,3).join(', ')} 역량에 주목했습니다.\n\n${unique.map(s=>`${s.title} 경험에서 ${s.summary}`).join('\n\n')}\n\n이 경험을 바탕으로 사용자에게 더 나은 제품 경험을 제공하고, 팀과 함께 측정 가능한 개선을 만들어가겠습니다.`:`${job.company} ${job.role} 지원 동기를 작성하세요. 연결된 경험 근거가 부족하므로 커리어 소재를 먼저 보완하는 것이 좋습니다.`;const d={id:'d'+Date.now(),title:`${job.company} · 맞춤 지원서`,jobId,content:body};state.docs.unshift(d);selectedDoc=d.id;save();toast('커리어 근거로 초안을 만들었습니다.');setTimeout(()=>setView('documents'),450)}
$('#jobForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const desc=fd.get('description').trim();const dictionary=['React','TypeScript','JavaScript','Next.js','Vue','Java','Spring','Python','AWS','Docker','Kubernetes','SQL','WebSocket','접근성','성능 최적화','디자인 시스템','A/B 테스트','사용자 경험','협업'];const skills=dictionary.filter(k=>desc.toLowerCase().includes(k.toLowerCase()));const matched=skills.filter(skill=>state.stories.some(s=>s.skills.some(x=>x.toLowerCase().includes(skill.toLowerCase())||skill.toLowerCase().includes(x.toLowerCase())))).length;const match=skills.length?Math.min(96,Math.round(48+(matched/skills.length)*48)):62;const job={id:'j'+Date.now(),company:fd.get('company'),role:fd.get('role'),deadline:fd.get('deadline'),url:fd.get('url'),description:desc,skills:skills.length?skills:['직무 역량','협업'],match,status:'관심'};state.jobs.unshift(job);save();e.currentTarget.reset();$('#jobModal').close();selectedJob=job.id;currentView='jobs';render();toast(`${skills.length}개 핵심 요건을 분석했습니다.`)});
$('#careerForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);state.stories.unshift({id:'s'+Date.now(),title:fd.get('title'),role:fd.get('role'),skills:fd.get('skills').split(',').map(x=>x.trim()).filter(Boolean),summary:fd.get('summary')});save();e.currentTarget.reset();$('#careerModal').close();render();toast('새 경험을 커리어 라이브러리에 저장했습니다.')});
document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>{if($('#mobileMenu').open)$('#mobileMenu').close();setView(x.dataset.view)}));document.querySelector('[data-action="open-mobile-menu"]')?.addEventListener('click',()=>$('#mobileMenu').showModal());document.querySelector('[data-action="close-mobile-menu"]')?.addEventListener('click',()=>$('#mobileMenu').close());$('#sidebarName').textContent=state.profile.name;$('#sidebarRole').textContent=state.profile.role;render();
